name: SimpleGates
version: 0.2.0
author: Lukas Gail
api-version: "1.15"
main: com.github.lukasgail.simplegates.SimpleGates
description: This plugin creates a special gate block that can be moved slowly. The block does not have to be placed to match other blocks and has no collision with other blocks
commands:
  gate:
    description: This command shows the help page.
    usage: /gate
    permission: gate.help
    permission-message: You don't have permission gate.help
  gate help:
    description: This command shows the help page.
    usage: /gate help
    permission: gate.help
    permission-message: You don't have permission gate.help
  gate sel:
    description: This command gives a selector tool.
    usage: /gate sel
    permission: gate.selector
    permission-message: You don't have permission gate.selector
  gate set:
    description: This command sets a new gate. Use force to set a gate bigger than 10 blocks.
    usage: /gate set <force | f>
    permission: gate.set
    permission-message: You don't have permission gate.set
  gate move:
    description: This command can move a gate manually.
    usage: /gate move [distance] <direction> <repetitions> <delay between moves>
    permission: gate.move
    permission-message: You don't have permission gate.move
  gate del:
    description: This command can delete a gate.
    usage: /gate del
    permission: gate.delete
    permission-message: You don't have permission gate.delete
  gate inv:
    description: This command can toggle the collision of a gate.
    usage: /gate inv [name]
    permission: gate.inv
    permission-message: You don't have permission gate.inv
  gate list:
    description: This command lists all available gates.
    usage: /gate list
    permission: gate.list
    permission-message: You don't have permission gate.list

permissions:
  gate.*:
    description: Gives access to all gate commands
    children:
      gate.help: true
      gate.selector: true
      gate.set: true
      gate.move: true
      gate.delete: true
      gate.inv: true
      gate.list: true
    default: op
  gate.selector:
    description: Allows you to get a gate-selector-tool to yourself
    default: op
  gate.help:
    description: Gives information about the SimpleGates plugin
    default: true